jetlinks/jetlinks-sdk

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/ai/cv/ImageData.java
- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/ai/cv/ObjectDetectionResult.java
检测输出的图片由原来的只有打标的图片，变成了不仅有打标的图片，还有原始图片
> refactor: 修改对象检测结果图像为多个；

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/commons/cmd/BatchBindDeviceCommand.java
- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/device/cmd/BatchBindDeviceCommand.java
- pom.xml
> feat(sdk): 新增设备批量绑定映射命令

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/device/cmd/BatchUnbindDeviceCommand.java
- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/device/cmd/UnbindDeviceCommand.java
> feat(sdk): 增加解除设备绑定映射相关命令

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/ai/cv/ImageData.java
> fix(SDK): 加入非空判断

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/ai/AiOutput.java
- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/ai/GenericAiOutput.java
> feat(SDK): ai输出结果新增源数据id字段

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/device/cmd/BatchUnbindDeviceCommand.java
> fix(sdk): 批量解绑设备使用泛型返回参数

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/commons/cmd/OperationByIdCommand.java
> fix(sdk): OperationByIdCommand命令增加Schema注解

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/media/GetPullStreamCommand.java
> fix(sdk):修改获取设备拉流地址命令返回类型

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/media/GetPullStreamCommand.java
> fix(sdk):获取拉流地址命令加入有效期配置

- jetlinks-sdk-generator/pom.xml
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/DefaultPomParser.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/MavenModel.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/PomParser.java
> feat(maven): maven解析

- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/DefaultPomParser.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/PomParser.java
> feat(pom): 输出文件流

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/device/DeviceInfo.java
> fix(sdk): DeviceInfo实体类增加describe设备描述字段

- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/DefaultPomParser.java
> fix(pom): pom

- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/DefaultPomParser.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/MavenModel.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/PomParser.java
> fix(pom): 修改使用逻辑

- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/pom/MavenModel.java
> feat(pom): 新增依赖

- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/JavaCodeParser.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/AnnotatedElementInfo.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/AnnotationInfo.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/AnnotationProperty.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/ClassInfo.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/FieldInfo.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/MethodInfo.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/PackageInfo.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/ParamInfo.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/enums/Modifier.java
- jetlinks-sdk-generator/src/main/java/org/jetlinks/sdk/generator/java/base/enums/Modifiers.java
1. 添加MethodInfo描述类中方法
2. 添加ParamInfo描述方法参数
3. ClassInfo添加泛型字段、方法信息字段、访问修饰符字段
> feat(sdk): 添加基础描述java属性的类;添加java代码解析接口

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/auth/AuthCommandSupportTypes.java
> feat(鉴权命令): 新增鉴权命令支持类型：菜单

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/device/cmd/SubscribeDevicePropertiesCommand.java
- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/device/cmd/SubscribeDevicePropertyCommand.java
> fix(设备命令): 订阅设备属性新增历史数据传参

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/device/DevicePropertyProperties.java
> feat(设备属性): 设备属性转换

- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/commons/cmd/DeleteByIdCommand.java
- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/commons/cmd/QueryListCommand.java
- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/commons/cmd/SaveCommand.java
- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/template/SaveByTemplateCommand.java
- jetlinks-sdk-api/src/main/java/org/jetlinks/sdk/server/utils/ConverterUtils.java
基于 https://github.com/jetlinks/jetlinks-core/pull/71
> refactor: 优化命令；迁移常用utils
